### ISSUE TITLE
Infrastructure task

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/email-parser#2]
Solve the following problem: for a given number print all the "simple" numbers which are less or equal to it. E.g. for 11 print out "2, 3, 5, 7, 11" in console. 

Requirements:
- Kotlin (!)
- Gradle build with the task: `run <N>` where N is the given number
- README should be enough for complete set up from scratch (i.e. I should be able to clone the repository, follow the instructions in README and get the result)
- N is from 2 to 1000, other values should be rejected
- Code should be in `playground` folder and follow standard Kotlin conventions: src/main/kotlin/... 

Hint:
Whichever IDE you prefer, IDE-specific files should NEVER be put under git.

**Comment by ppzhuk** [comment]
Done.
