### ISSUE TITLE
Implement reading message from an EML file

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/email-parser#4]
Write a pure library (pure == without side-effects; the API in it should accept a data and return a data without any IO operations) and an executable which will do the following: 
- Read the path to EML file (executable input)
- Get the EML file data (library input; in a form of text or some specific java-mail data structure; use your judgement)
- Return a structure, containing the subject and  the decoded text of the message (library output)
- Print out the subject and the body (executable output)
  Don't forget to write tests for the library (the executable shouldn't be covered with tests, as it is just a demo).
  Note: the idea of this task is to prepare an infrastructure and the wire for the further work.

**Comment by ppzhuk** [comment]
Completed

**Comment by ppzhuk** [comment]
completed
