### ISSUE TITLE
Pass properties to gradle task

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/email-parser#6]
Find a way to pass a property to the task (either via gradle properties or via JVM properties) and use it for both playground and main task.

**Comment by ppzhuk** [comment]
I have added passing command-line arguments through gradle run task in a way `gradlew run -PN="num"`, where num is desired number.

I decided not to change much previously made user interaction. So if you wouldn't pass any arguments (e.g. simple execute `gradlew run`) or argument is incorrect than you get prompt to enter the number again as before.
