### ISSUE TITLE
Can't run tests on Ubuntu

### ISSUE THREAD

**Issue by mariyadavydova** [JetBrains/email-parser#7]
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestKotlin UP-TO-DATE
:compileTestJava UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:test

practice.email.parser.MailParserSpecs > initializationError FAILED
    java.lang.ExceptionInInitializerError
        Caused by: java.nio.file.NoSuchFileException

practice.email.parser.ContentParserSpec > initializationError FAILED
    java.lang.NoClassDefFoundError

12 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':test'.
  
  > There were failing tests. See the report at: file:///home/mariya/projects/students/email-parser/build/reports/tests/index.html
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5.303 secs

**Comment by ppzhuk** [comment]
fixed
