### ISSUE TITLE
text/HTML content type will be added soon.

### ISSUE THREAD

**Issue by patelhr** [JetBrains/email-parser#8]
Hello,
Great library for mail parsing.
I would like to know when this will be added "text/HTML content type will be added soon".
Eagerly waiting for this feature.

Thanks

**Comment by patelhr** [comment]
Hello @mariyadavydova
Please give any updates on above enhancement.

Thanks

**Comment by simondoescode** [comment]
+1

**Comment by ppzhuk** [comment]
Unfortunately there is no any particular time estimate as it is a one of the side projects. But you are always welcome to make a pull request :)
